language: java

dist: xenial
sudo: false

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

git:
  depth: false

addons:
  sonarcloud:
    organization: sanyarnd-github
    token:
      secure: $SONAR_API_KEY

before_install:
  - chmod +x mvnw
install:
  mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -B -V

after_success:
  - mvn org.jacoco:jacoco-maven-plugin:report
  - mvn pvsstudio:pvsCredentials pvsstudio:pvsAnalyze
  - mvn spotbugs:spotbugs
  - mvn pmd:pmd
  - mvn sonar:sonar -DskipTests=true

deploy:
  - provider: releases
    api_key: $GITHUB_API_KEY
    file:
      - /home/travis/build/sanyarnd/applocker/target/app-locker-$TRAVIS_TAG.jar
      - /home/travis/build/sanyarnd/applocker/target/app-locker-$TRAVIS_TAG-javadoc.jar
      - /home/travis/build/sanyarnd/applocker/target/app-locker-$TRAVIS_TAG-sources.jar
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: "mvn --settings .m2/settings.xml deploy"
    skip_cleanup: true
    on:
      tags: true
