language: java

dist: xenial
sudo: false

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
    - $HOME/.mvn

git:
  depth: false

addons:
  sonarcloud:
    organization: sanyarnd-github
    token:
      secure: $SONAR_API_KEY

before_install:
  - chmod +x mvnw
install: ./mvnw clean install
  --activate-profiles checkstyle,integration-tests,with-coverage,create-javadoc-and-sources,logging
  --batch-mode --show-version --no-transfer-progress --errors
script: skip
after_success:
  - ./mvnw sonar:sonar -DskipTests=true --activate-profiles analysis-plugins
    --show-version --no-transfer-progress --errors

before_deploy:
  - cp -r target/apidocs gh-pages
  - cp README.md gh-pages/README.md
  - cp CHANGELOG.md gh-pages/CHANGELOG.md
deploy:
  - provider: pages
    github_token: $GITHUB_API_KEY
    local_dir: gh-pages
    skip_cleanup: true
    on:
      branch: master
  - provider: releases
    api_key: $GITHUB_API_KEY
    file:
      - /home/travis/build/sanyarnd/applocker/target/app-locker-$TRAVIS_TAG.jar
      - /home/travis/build/sanyarnd/applocker/target/app-locker-$TRAVIS_TAG-javadoc.jar
      - /home/travis/build/sanyarnd/applocker/target/app-locker-$TRAVIS_TAG-sources.jar
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: ./mvnw deploy --settings .m2/settings.xml -DskipTests
      --activate-profiles deploy-bintray,create-javadoc-and-sources
      --show-version --no-transfer-progress --errors
    skip_cleanup: true
    on:
      tags: true
