language: java

dist: xenial
sudo: false

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

git:
  depth: false

addons:
  sonarcloud:
    organization: sanyarnd-github
    token:
      secure: $SONAR_API_KEY

install: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install org.jacoco:jacoco-maven-plugin:report -B -V

before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

after_success:
  - mvn pvsstudio:pvsCredentials
  - mvn pvsstudio:pvsAnalyze
  - mvn sonar:sonar -DskipTests=true
  - fossa init
  - fossa analyze

deploy:
  - provider: releases
    api_key: $GITHUB_API_KEY
    file:
      - /home/travis/build/sanyarnd/applocker/target/app-locker-$TRAVIS_TAG.jar
      - /home/travis/build/sanyarnd/applocker/target/app-locker-$TRAVIS_TAG-javadoc.jar
      - /home/travis/build/sanyarnd/applocker/target/app-locker-$TRAVIS_TAG-sources.jar
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: "cp .m2/settings.xml $HOME/.m2/settings.xml && mvn deploy"
    skip_cleanup: true
    on:
      tags: true
