theme: jekyll-theme-slate

title: AppLocker
description: Provides file-based locking mechanism with inter-process communication support

show_downloads: true

github:
  jar_url: https://github.com/sanyarnd/applocker/releases
  pom_url: https://bintray.com/sanya-rnd/maven-projects/applocker
  api_url: https://sanyarnd.github.io/applocker/apidocs/index.html
